language: python

git:
  depth: 1

fast_finish: true

matrix:
    include:
        - os: osx
          language: generic
          env: PY=3.6
          before_install:
                - brew uninstall python mercurial postgis sfcgal cgal gdal
                - brew update
                - brew upgrade
                - brew tap osgeo/osgeo4mac
                - brew outdated gdal  || brew upgrade gdal
                - brew outdated gdal2 || brew upgrade gdal2
                - brew install jq
                - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
                - bash miniconda.sh -b -p $HOME/miniconda
                - export PATH="$HOME/miniconda/bin:$PATH"
                - hash -r
                - conda update --yes conda
                - conda info -a
                - conda config --add channels conda-forge
                - conda create --yes -n test-natural-earth python=$PY
                - source activate test-natural-earth
                - echo $(python --version)
                - conda install --yes -c conda-forge fiona
                - python -c "import fiona"
                - conda install --yes -c conda-forge sparqlwrapper
                - conda install --yes -c conda-forge requests
                - pip install csvtomd

        - os: linux
          env: PY=3.6
          sudo: required          
          before_install:
                - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
                - sudo apt-get --yes --force-yes update -qq
                - sudo apt-get install --yes gdal-bin jq
                - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh  -O miniconda.sh
                - bash miniconda.sh -b -p $HOME/miniconda
                - export PATH="$HOME/miniconda/bin:$PATH"
                - hash -r
                - conda update --yes conda
                - conda info -a
                - conda config --add channels conda-forge
                - conda create --yes -n test-natural-earth python=$PY
                - source activate test-natural-earth
                - echo $(python --version)
                - conda install --yes -c conda-forge fiona
                - python -c "import fiona"
                - conda install --yes -c conda-forge sparqlwrapper
                - conda install --yes -c conda-forge requests
                - pip install csvtomd

        - language: python
          python: 3.6
          os: linux
          sudo: required          
          before_install:
                - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
                - sudo apt-get --yes --force-yes update -qq
                - sudo apt-get install --yes gdal-bin jq
                - pip3 install -U SPARQLWrapper
                - pip3 install -U fiona
                - python -c "import fiona"                
                - pip3 install -U csvtomd
                - pip3 install -U requests



        - language: python
          python: 3.5
          os: linux
          sudo: required          
          before_install:
                - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
                - sudo apt-get --yes --force-yes update -qq
                - sudo apt-get install --yes gdal-bin jq
                - pip3 install -U SPARQLWrapper
                - pip3 install -U fiona
                - python -c "import fiona"                
                - pip3 install -U csvtomd
                - pip3 install -U requests


script:
  - python3 ./tools/wikidata/platform_debug_info.py
  - time ./tools/wikidata/update.sh fetch
  - time ./tools/wikidata/update.sh write
  - cat   x_tempshape/update.md
  - cp -r x_tempshape/10m_cultural/*    10m_cultural/
  - cp -r x_tempshape/10m_physical/*    10m_physical/
  - make clean all
